TDataSet *CreateTable() { 
// -----------------------------------------------------------------
// bfc/.make/db/.const/StarDb/Geometry/tpc/.tpcDimensions/tpcDimensions Allocated rows: 1  Used rows: 1  Row size: 964 bytes
//  Table: tpcDimensions_st[0]--> tpcDimensions_st[0]
// ====================================================================
// ------  Test whether this table share library was loaded ------
  if (!TClass::GetClass("St_tpcDimensions")) return 0;
tpcDimensions_st row;
St_tpcDimensions *tableSet = new St_tpcDimensions("tpcDimensions",1);
//
memset(&row,0,tableSet->GetRowSize());
    row.numberOfSectors	 =         24; // ;
    row.tpcInnerRadius	 =     46.107; // ;
    row.tpcOuterRadius	 =     207.75; // ;
    row.tpcTotalLength	 =     459.37; // ;
    row.wheelInnerRadius	 =       49.6; // ;
    row.wheelOuterRadius	 =     206.75; // ;
    row.wheelThickness	 =      11.43; // ;
    row.senseGasOuterRadius	 =        200; // ;
    row.tpeaThickness	 =        9.7; // ;
    row.cathodeInnerRadius	 =     46.825; // ;
    row.cathodeOuterRadius	 =        200; // ;
    row.cathodeThickness	 =     0.0076; // ;
    row.outerCuThickness	 =      0.031; // ;
    row.outerKaptonThickness	 =      0.015; // ;
    row.outerNomexThickness	 =          1; // ;
    row.outerGlueThickness	 =       0.02; // ;
    row.outerInsGasThickness	 =        5.7; // ;
    row.outerAlThickness	 =        0.4; // ;
    row.outerAlHoneycombThickness	 =        0.6; // ;
    row.innerGlueThickness	 =       0.08; // ;
    row.innerNomexThickness	 =       1.27; // ;
    row.innerKaptonThickness	 =      0.015; // ;
    row.innerAlThickness	 =      0.004; // ;
    row.innerGapWidI	 =      21.82; // inner width of air in support wheel  ;
    row.innerGapWidO	 =      55.12; // outer width of air in support wheel  ;
    row.innerGapHeit	 =      62.15; // height (dr) of air in support wheel  ;
    row.innerGapRad	 =       87.6; // air in support wheel - center radius  ;
    row.innerInWidth	 =       27.5; // sector width at inner radius  ;
    row.innerOutWidth	 =      64.76; // sector width at outer radius  ;
    row.innerHeight	 =      69.52; // sector radial height  ;
    row.innerPPDepth	 =       1.67; // padplane thickness (Al+pcb)  ;
    row.innerAlDepth	 =       6.99; // depth of openings in Al structure  ;
    row.innerMWCDepth	 =        0.4; // full thickness MWC sensitive region  ;
    row.innerBoundary	 =       3.74; // Al frame boundary width  ;
    row.innerRCenter	 =     86.669; // sector center radius (precision hole)  ;
    row.innerMWCInn	 =      26.48; // MWC sensitive region inner size  ;
    row.innerMWCOut	 =      60.76; // MWC sensitive region outer size  ;
    row.innerMVCHei	 =         64; // MVC sensitive region radial  ;
    row.innerAirGaps	 =          5; // number of air gaps in Al  ;
    row.innerExtraAl	 =          0; // number of extra Al supportpieces  ;
    row.innerZGaps[0]	 =       6.67; // opening positions  ;
    row.innerZGaps[1]	 =      18.22;
    row.innerZGaps[2]	 =      34.22;
    row.innerZGaps[3]	 =      50.22;
    row.innerZGaps[4]	 =      62.65;
    row.innerZGapsSize[0]	 =       6.13; // opening size  ;
    row.innerZGapsSize[1]	 =      15.05;
    row.innerZGapsSize[2]	 =      15.05;
    row.innerZGapsSize[3]	 =      15.05;
    row.innerZGapsSize[4]	 =       7.09;
    row.innerXExtraAl[0]	 =          0; // x positions  ;
    row.innerXExtraAl[1]	 =          0;
    row.innerXExtraAl[2]	 =          0;
    row.innerXExtraAl[3]	 =          0;
    row.innerXExtraAl[4]	 =          0;
    row.innerZExtraAl[0]	 =          0; // z positions  ;
    row.innerZExtraAl[1]	 =          0;
    row.innerZExtraAl[2]	 =          0;
    row.innerZExtraAl[3]	 =          0;
    row.innerZExtraAl[4]	 =          0;
    row.innerDXExtraAl[0]	 =          0; // x thickness  ;
    row.innerDXExtraAl[1]	 =          0;
    row.innerDXExtraAl[2]	 =          0;
    row.innerDXExtraAl[3]	 =          0;
    row.innerDXExtraAl[4]	 =          0;
    row.innerDZExtraAl[0]	 =          0; // z thickness  ;
    row.innerDZExtraAl[1]	 =          0;
    row.innerDZExtraAl[2]	 =          0;
    row.innerDZExtraAl[3]	 =          0;
    row.innerDZExtraAl[4]	 =          0;
    row.outerGapWidI	 =      57.84; // inner width of air in support wheel  ;
    row.outerGapWidO	 =      93.48; // outer width of air in support wheel  ;
    row.outerGapHeit	 =      66.47; // height (dr) of air in support wheel  ;
    row.outerGapRad	 =     157.34; // air in support wheel - center radius  ;
    row.outerInWidth	 =      64.92; // sector width at inner radius  ;
    row.outerOutWidth	 =     103.25; // sector width at outer radius  ;
    row.outerHeight	 =      71.51; // sector radial height  ;
    row.outerPPDepth	 =       1.27; // padplane thickness (Al+pcb)  ;
    row.outerAlDepth	 =       6.99; // depth of openings in Al structure  ;
    row.outerMWCDepth	 =        0.8; // full thickness MWC sensitive region  ;
    row.outerBoundary	 =       3.74; // Al frame boundary width  ;
    row.outerRCenter	 =    157.488; // sector center radius (precision hole)  ;
    row.outerMWCInn	 =      63.98; // MWC sensitive region inner size  ;
    row.outerMWCOut	 =      98.28; // MWC sensitive region outer size  ;
    row.outerMVCHei	 =         64; // MVC sensitive region radial  ;
    row.outerAirGaps	 =          8; // number of air gaps in Al  ;
    row.outerExtraAl	 =          5; // number of extra Al supportpieces  ;
    row.outerZGaps[0]	 =      8.216; // opening positions  ;
    row.outerZGaps[1]	 =     16.217;
    row.outerZGaps[2]	 =     24.218;
    row.outerZGaps[3]	 =     32.219;
    row.outerZGaps[4]	 =      40.22;
    row.outerZGaps[5]	 =     48.221;
    row.outerZGaps[6]	 =     56.222;
    row.outerZGaps[7]	 =     64.143;
    row.outerZGapsSize[0]	 =       7.05; // opening size  ;
    row.outerZGapsSize[1]	 =       7.05;
    row.outerZGapsSize[2]	 =       7.05;
    row.outerZGapsSize[3]	 =       7.05;
    row.outerZGapsSize[4]	 =       7.05;
    row.outerZGapsSize[5]	 =       7.05;
    row.outerZGapsSize[6]	 =       7.05;
    row.outerZGapsSize[7]	 =       6.89;
    row.outerXExtraAl[0]	 =          0; // x positions  ;
    row.outerXExtraAl[1]	 =          0;
    row.outerXExtraAl[2]	 =          0;
    row.outerXExtraAl[3]	 =    -21.907;
    row.outerXExtraAl[4]	 =     21.907;
    row.outerZExtraAl[0]	 =       6.69; // z positions  ;
    row.outerZExtraAl[1]	 =      32.22;
    row.outerZExtraAl[2]	 =      40.22;
    row.outerZExtraAl[3]	 =      56.22;
    row.outerZExtraAl[4]	 =      56.22;
    row.outerDXExtraAl[0]	 =       2.54; // x thickness  ;
    row.outerDXExtraAl[1]	 =      0.476;
    row.outerDXExtraAl[2]	 =      0.476;
    row.outerDXExtraAl[3]	 =      3.175;
    row.outerDXExtraAl[4]	 =      3.175;
    row.outerDZExtraAl[0]	 =          4; // z thickness  ;
    row.outerDZExtraAl[1]	 =       7.05;
    row.outerDZExtraAl[2]	 =       7.05;
    row.outerDZExtraAl[3]	 =       7.05;
    row.outerDZExtraAl[4]	 =       7.05;
tableSet->AddAt(&row);
// ----------------- end of code ---------------
 return (TDataSet *)tableSet;
}
