TDataSet *CreateTable() { 
// -----------------------------------------------------------------
// bfc/.make/db/.const/StarDb/Calibrations/tpc/.tpcAltroParams/tpcAltroParams Allocated rows: 24  Used rows: 24  Row size: 36 bytes
//  Table: tpcAltroParams_st[0]--> tpcAltroParams_st[23]
// ====================================================================
// ------  Test whether this table share library was loaded ------
  if (!TClass::GetClass("St_tpcAltroParams")) return 0;
tpcAltroParams_st row;
St_tpcAltroParams *tableSet = new St_tpcAltroParams("tpcAltroParams",24);
//
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.N	 =          6; // = no. of Altro parameters ;
    row.Altro_thr	 =          4; // ;
    row.Altro_seq	 =          2; // ;
    row.Altro_K1	 =      57158; // ;
    row.Altro_K2	 =      21787; // ;
    row.Altro_K3	 =      26699; // ;
    row.Altro_L1	 =       7449; // ;
    row.Altro_L2	 =      37911; // ;
    row.Altro_L3	 =      58775; // ;
tableSet->AddAt(&row);
// ----------------- end of code ---------------
 return (TDataSet *)tableSet;
}
