TDataSet *CreateTable() { 
// -----------------------------------------------------------------
// bfc/.make/db/.const/StarDb/Calibrations/tpc/.tpcRDOMap/tpcRDOMap Allocated rows: 49  Used rows: 49  Row size: 12 bytes
//  Table: tpcRDOMap_st[0]--> tpcRDOMap_st[48]
// ====================================================================
// ------  Test whether this table share library was loaded ------
  if (!TClass::GetClass("St_tpcRDOMap")) return 0;
tpcRDOMap_st row;
St_tpcRDOMap *tableSet = new St_tpcRDOMap("tpcRDOMap",49);
//
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          1; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x1; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x58; // ;
    row.rdo	 =         0x1; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          2; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x2; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x60; // ;
    row.rdo	 =         0x1; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          3; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x3; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x68; // ;
    row.rdo	 =         0x1; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          4; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x4; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x70; // ;
    row.rdo	 =         0x1; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          5; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x5; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x76; // ;
    row.rdo	 =         0x1; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          6; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x6; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x2; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          7; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x6; // ;
    row.padMin	 =         0x3; // ;
    row.padMax	 =         0x7c; // ;
    row.rdo	 =         0x1; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          8; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x6; // ;
    row.padMin	 =         0x7d; // ;
    row.padMax	 =         0x7e; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =          9; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x7; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x23; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         10; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x7; // ;
    row.padMin	 =         0x24; // ;
    row.padMax	 =         0x63; // ;
    row.rdo	 =         0x1; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         11; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x7; // ;
    row.padMin	 =         0x64; // ;
    row.padMax	 =         0x86; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         12; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x8; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x8e; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         13; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x9; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x96; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         14; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0xa; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x9e; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         15; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0xb; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0xa6; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         16; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0xc; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0xae; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         17; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0xd; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0xb6; // ;
    row.rdo	 =         0x2; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         18; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0xe; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x62; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         19; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0xf; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x64; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         20; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x10; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x66; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         21; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x11; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x68; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         22; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x12; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x6a; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         23; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x13; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x6a; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         24; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x14; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x6c; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         25; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x15; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x6e; // ;
    row.rdo	 =         0x3; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         26; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x16; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x70; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         27; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x17; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x70; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         28; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x18; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x72; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         29; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x19; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x74; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         30; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x1a; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x76; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         31; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x1b; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x78; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         32; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x1c; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x7a; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         33; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x1d; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x7a; // ;
    row.rdo	 =         0x4; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         34; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x1e; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x7c; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         35; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x1f; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x7e; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         36; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x20; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x80; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         37; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x21; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x80; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         38; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x22; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x82; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         39; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x23; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x84; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         40; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x24; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x86; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         41; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x25; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x88; // ;
    row.rdo	 =         0x5; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         42; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x26; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x8a; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         43; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x27; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x8a; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         44; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x28; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x8c; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         45; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x29; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x8e; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         46; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x2a; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x90; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         47; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x2b; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x90; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         48; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x2c; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x90; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
memset(&row,0,tableSet->GetRowSize());
    row.idx	 =         49; // ;
    row.nrows	 =         49; // ;
    row.row	 =         0x2d; // ;
    row.padMin	 =         0x1; // ;
    row.padMax	 =         0x90; // ;
    row.rdo	 =         0x6; // ;
tableSet->AddAt(&row);
// ----------------- end of code ---------------
 return (TDataSet *)tableSet;
}
